// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: marshal/v1/daemon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// M6 — log stream selector.
type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0 // merged (default)
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_marshal_v1_daemon_proto_enumTypes[0].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_marshal_v1_daemon_proto_enumTypes[0]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AppSpec mirrors config.App. kill_timeout is a Go duration string ("5s").
type AppSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Instances     int32                  `protobuf:"varint,5,opt,name=instances,proto3" json:"instances,omitempty"`
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Restart       string                 `protobuf:"bytes,7,opt,name=restart,proto3" json:"restart,omitempty"` // always | on-failure | no
	MaxRestarts   int32                  `protobuf:"varint,8,opt,name=max_restarts,json=maxRestarts,proto3" json:"max_restarts,omitempty"`
	KillTimeout   string                 `protobuf:"bytes,9,opt,name=kill_timeout,json=killTimeout,proto3" json:"kill_timeout,omitempty"`
	Logs          *LogRetention          `protobuf:"bytes,10,opt,name=logs,proto3,oneof" json:"logs,omitempty"` // M6 per-app retention override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppSpec) Reset() {
	*x = AppSpec{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpec) ProtoMessage() {}

func (x *AppSpec) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpec.ProtoReflect.Descriptor instead.
func (*AppSpec) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *AppSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpec) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *AppSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AppSpec) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *AppSpec) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *AppSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *AppSpec) GetRestart() string {
	if x != nil {
		return x.Restart
	}
	return ""
}

func (x *AppSpec) GetMaxRestarts() int32 {
	if x != nil {
		return x.MaxRestarts
	}
	return 0
}

func (x *AppSpec) GetKillTimeout() string {
	if x != nil {
		return x.KillTimeout
	}
	return ""
}

func (x *AppSpec) GetLogs() *LogRetention {
	if x != nil {
		return x.Logs
	}
	return nil
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*AppSpec             `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *StartRequest) GetApps() []*AppSpec {
	if x != nil {
		return x.Apps
	}
	return nil
}

// Selector resolves to a name, a numeric id, or the literal "all".
type Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *Selector) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// ProcInfo mirrors a supervised instance snapshot. cpu/mem are reserved for M3.
type ProcInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InstanceId    int32                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,6,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	Restarts      int32                  `protobuf:"varint,7,opt,name=restarts,proto3" json:"restarts,omitempty"`
	Cpu           float64                `protobuf:"fixed64,8,opt,name=cpu,proto3" json:"cpu,omitempty"` // M3
	Mem           int64                  `protobuf:"varint,9,opt,name=mem,proto3" json:"mem,omitempty"`  // M3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcInfo) Reset() {
	*x = ProcInfo{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcInfo) ProtoMessage() {}

func (x *ProcInfo) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcInfo.ProtoReflect.Descriptor instead.
func (*ProcInfo) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *ProcInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProcInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcInfo) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *ProcInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProcInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcInfo) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *ProcInfo) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *ProcInfo) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ProcInfo) GetMem() int64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

type ProcList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Procs         []*ProcInfo            `protobuf:"bytes,1,rep,name=procs,proto3" json:"procs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcList) Reset() {
	*x = ProcList{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcList) ProtoMessage() {}

func (x *ProcList) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcList.ProtoReflect.Descriptor instead.
func (*ProcList) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *ProcList) GetProcs() []*ProcInfo {
	if x != nil {
		return x.Procs
	}
	return nil
}

// M3 — log streaming.
type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Lines         int32                  `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	Stream        LogStream              `protobuf:"varint,4,opt,name=stream,proto3,enum=marshal.v1.LogStream" json:"stream,omitempty"` // M6
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *LogRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LogRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *LogRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogRequest) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

// M6 — per-app log retention settings.
type LogRetention struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxSizeMb     *int32                 `protobuf:"varint,1,opt,name=max_size_mb,json=maxSizeMb,proto3,oneof" json:"max_size_mb,omitempty"`
	MaxBackups    *int32                 `protobuf:"varint,2,opt,name=max_backups,json=maxBackups,proto3,oneof" json:"max_backups,omitempty"`
	MaxAgeDays    *int32                 `protobuf:"varint,3,opt,name=max_age_days,json=maxAgeDays,proto3,oneof" json:"max_age_days,omitempty"`
	Compress      *bool                  `protobuf:"varint,4,opt,name=compress,proto3,oneof" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRetention) Reset() {
	*x = LogRetention{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRetention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRetention) ProtoMessage() {}

func (x *LogRetention) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRetention.ProtoReflect.Descriptor instead.
func (*LogRetention) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *LogRetention) GetMaxSizeMb() int32 {
	if x != nil && x.MaxSizeMb != nil {
		return *x.MaxSizeMb
	}
	return 0
}

func (x *LogRetention) GetMaxBackups() int32 {
	if x != nil && x.MaxBackups != nil {
		return *x.MaxBackups
	}
	return 0
}

func (x *LogRetention) GetMaxAgeDays() int32 {
	if x != nil && x.MaxAgeDays != nil {
		return *x.MaxAgeDays
	}
	return 0
}

func (x *LogRetention) GetCompress() bool {
	if x != nil && x.Compress != nil {
		return *x.Compress
	}
	return false
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InstanceId    int32                  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Stderr        bool                   `protobuf:"varint,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Line          string                 `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *LogLine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogLine) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *LogLine) GetStderr() bool {
	if x != nil {
		return x.Stderr
	}
	return false
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// M5 — metric history.
type MetricsHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`                  // name or id, resolved like logs/describe
	SinceMs       int64                  `protobuf:"varint,2,opt,name=since_ms,json=sinceMs,proto3" json:"since_ms,omitempty"`    // lookback window in ms; server queries ts >= now - since_ms
	BucketMs      int64                  `protobuf:"varint,3,opt,name=bucket_ms,json=bucketMs,proto3" json:"bucket_ms,omitempty"` // bucket width in ms; 0 = server auto-picks (~60 buckets)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsHistoryRequest) Reset() {
	*x = MetricsHistoryRequest{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsHistoryRequest) ProtoMessage() {}

func (x *MetricsHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsHistoryRequest.ProtoReflect.Descriptor instead.
func (*MetricsHistoryRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsHistoryRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *MetricsHistoryRequest) GetSinceMs() int64 {
	if x != nil {
		return x.SinceMs
	}
	return 0
}

func (x *MetricsHistoryRequest) GetBucketMs() int64 {
	if x != nil {
		return x.BucketMs
	}
	return 0
}

type MetricBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	CpuAvg        float64                `protobuf:"fixed64,2,opt,name=cpu_avg,json=cpuAvg,proto3" json:"cpu_avg,omitempty"`
	CpuMax        float64                `protobuf:"fixed64,3,opt,name=cpu_max,json=cpuMax,proto3" json:"cpu_max,omitempty"`
	MemAvg        uint64                 `protobuf:"varint,4,opt,name=mem_avg,json=memAvg,proto3" json:"mem_avg,omitempty"`
	MemMax        uint64                 `protobuf:"varint,5,opt,name=mem_max,json=memMax,proto3" json:"mem_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBucket) Reset() {
	*x = MetricBucket{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBucket) ProtoMessage() {}

func (x *MetricBucket) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBucket.ProtoReflect.Descriptor instead.
func (*MetricBucket) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *MetricBucket) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *MetricBucket) GetCpuAvg() float64 {
	if x != nil {
		return x.CpuAvg
	}
	return 0
}

func (x *MetricBucket) GetCpuMax() float64 {
	if x != nil {
		return x.CpuMax
	}
	return 0
}

func (x *MetricBucket) GetMemAvg() uint64 {
	if x != nil {
		return x.MemAvg
	}
	return 0
}

func (x *MetricBucket) GetMemMax() uint64 {
	if x != nil {
		return x.MemMax
	}
	return 0
}

type MetricsHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*MetricBucket        `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsHistoryResponse) Reset() {
	*x = MetricsHistoryResponse{}
	mi := &file_marshal_v1_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsHistoryResponse) ProtoMessage() {}

func (x *MetricsHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsHistoryResponse.ProtoReflect.Descriptor instead.
func (*MetricsHistoryResponse) Descriptor() ([]byte, []int) {
	return file_marshal_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *MetricsHistoryResponse) GetBuckets() []*MetricBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_marshal_v1_daemon_proto protoreflect.FileDescriptor

const file_marshal_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x17marshal/v1/daemon.proto\x12\n" +
	"marshal.v1\"\a\n" +
	"\x05Empty\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf7\x02\n" +
	"\aAppSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x1c\n" +
	"\tinstances\x18\x05 \x01(\x05R\tinstances\x12.\n" +
	"\x03env\x18\x06 \x03(\v2\x1c.marshal.v1.AppSpec.EnvEntryR\x03env\x12\x18\n" +
	"\arestart\x18\a \x01(\tR\arestart\x12!\n" +
	"\fmax_restarts\x18\b \x01(\x05R\vmaxRestarts\x12!\n" +
	"\fkill_timeout\x18\t \x01(\tR\vkillTimeout\x121\n" +
	"\x04logs\x18\n" +
	" \x01(\v2\x18.marshal.v1.LogRetentionH\x00R\x04logs\x88\x01\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_logs\"7\n" +
	"\fStartRequest\x12'\n" +
	"\x04apps\x18\x01 \x03(\v2\x13.marshal.v1.AppSpecR\x04apps\"\"\n" +
	"\bSelector\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\xd4\x01\n" +
	"\bProcInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x05R\n" +
	"instanceId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x1b\n" +
	"\tuptime_ms\x18\x06 \x01(\x03R\buptimeMs\x12\x1a\n" +
	"\brestarts\x18\a \x01(\x05R\brestarts\x12\x10\n" +
	"\x03cpu\x18\b \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03mem\x18\t \x01(\x03R\x03mem\"6\n" +
	"\bProcList\x12*\n" +
	"\x05procs\x18\x01 \x03(\v2\x14.marshal.v1.ProcInfoR\x05procs\"\x81\x01\n" +
	"\n" +
	"LogRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12-\n" +
	"\x06stream\x18\x04 \x01(\x0e2\x15.marshal.v1.LogStreamR\x06stream\"\xdf\x01\n" +
	"\fLogRetention\x12#\n" +
	"\vmax_size_mb\x18\x01 \x01(\x05H\x00R\tmaxSizeMb\x88\x01\x01\x12$\n" +
	"\vmax_backups\x18\x02 \x01(\x05H\x01R\n" +
	"maxBackups\x88\x01\x01\x12%\n" +
	"\fmax_age_days\x18\x03 \x01(\x05H\x02R\n" +
	"maxAgeDays\x88\x01\x01\x12\x1f\n" +
	"\bcompress\x18\x04 \x01(\bH\x03R\bcompress\x88\x01\x01B\x0e\n" +
	"\f_max_size_mbB\x0e\n" +
	"\f_max_backupsB\x0f\n" +
	"\r_max_age_daysB\v\n" +
	"\t_compress\"j\n" +
	"\aLogLine\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x05R\n" +
	"instanceId\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\bR\x06stderr\x12\x12\n" +
	"\x04line\x18\x04 \x01(\tR\x04line\"k\n" +
	"\x15MetricsHistoryRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x19\n" +
	"\bsince_ms\x18\x02 \x01(\x03R\asinceMs\x12\x1b\n" +
	"\tbucket_ms\x18\x03 \x01(\x03R\bbucketMs\"\x87\x01\n" +
	"\fMetricBucket\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x17\n" +
	"\acpu_avg\x18\x02 \x01(\x01R\x06cpuAvg\x12\x17\n" +
	"\acpu_max\x18\x03 \x01(\x01R\x06cpuMax\x12\x17\n" +
	"\amem_avg\x18\x04 \x01(\x04R\x06memAvg\x12\x17\n" +
	"\amem_max\x18\x05 \x01(\x04R\x06memMax\"L\n" +
	"\x16MetricsHistoryResponse\x122\n" +
	"\abuckets\x18\x01 \x03(\v2\x18.marshal.v1.MetricBucketR\abuckets*U\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x022\xe9\x04\n" +
	"\x06Daemon\x127\n" +
	"\x05Start\x12\x18.marshal.v1.StartRequest\x1a\x14.marshal.v1.ProcList\x122\n" +
	"\x04Stop\x12\x14.marshal.v1.Selector\x1a\x14.marshal.v1.ProcList\x125\n" +
	"\aRestart\x12\x14.marshal.v1.Selector\x1a\x14.marshal.v1.ProcList\x124\n" +
	"\x06Delete\x12\x14.marshal.v1.Selector\x1a\x14.marshal.v1.ProcList\x12/\n" +
	"\x04List\x12\x11.marshal.v1.Empty\x1a\x14.marshal.v1.ProcList\x126\n" +
	"\bDescribe\x12\x14.marshal.v1.Selector\x1a\x14.marshal.v1.ProcList\x12*\n" +
	"\x04Save\x12\x11.marshal.v1.Empty\x1a\x0f.marshal.v1.Ack\x124\n" +
	"\tResurrect\x12\x11.marshal.v1.Empty\x1a\x14.marshal.v1.ProcList\x12*\n" +
	"\x04Kill\x12\x11.marshal.v1.Empty\x1a\x0f.marshal.v1.Ack\x125\n" +
	"\x04Logs\x12\x16.marshal.v1.LogRequest\x1a\x13.marshal.v1.LogLine0\x01\x12W\n" +
	"\x0eMetricsHistory\x12!.marshal.v1.MetricsHistoryRequest\x1a\".marshal.v1.MetricsHistoryResponseB\x18Z\x16marshal/internal/pb;pbb\x06proto3"

var (
	file_marshal_v1_daemon_proto_rawDescOnce sync.Once
	file_marshal_v1_daemon_proto_rawDescData []byte
)

func file_marshal_v1_daemon_proto_rawDescGZIP() []byte {
	file_marshal_v1_daemon_proto_rawDescOnce.Do(func() {
		file_marshal_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marshal_v1_daemon_proto_rawDesc), len(file_marshal_v1_daemon_proto_rawDesc)))
	})
	return file_marshal_v1_daemon_proto_rawDescData
}

var file_marshal_v1_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_marshal_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_marshal_v1_daemon_proto_goTypes = []any{
	(LogStream)(0),                 // 0: marshal.v1.LogStream
	(*Empty)(nil),                  // 1: marshal.v1.Empty
	(*Ack)(nil),                    // 2: marshal.v1.Ack
	(*AppSpec)(nil),                // 3: marshal.v1.AppSpec
	(*StartRequest)(nil),           // 4: marshal.v1.StartRequest
	(*Selector)(nil),               // 5: marshal.v1.Selector
	(*ProcInfo)(nil),               // 6: marshal.v1.ProcInfo
	(*ProcList)(nil),               // 7: marshal.v1.ProcList
	(*LogRequest)(nil),             // 8: marshal.v1.LogRequest
	(*LogRetention)(nil),           // 9: marshal.v1.LogRetention
	(*LogLine)(nil),                // 10: marshal.v1.LogLine
	(*MetricsHistoryRequest)(nil),  // 11: marshal.v1.MetricsHistoryRequest
	(*MetricBucket)(nil),           // 12: marshal.v1.MetricBucket
	(*MetricsHistoryResponse)(nil), // 13: marshal.v1.MetricsHistoryResponse
	nil,                            // 14: marshal.v1.AppSpec.EnvEntry
}
var file_marshal_v1_daemon_proto_depIdxs = []int32{
	14, // 0: marshal.v1.AppSpec.env:type_name -> marshal.v1.AppSpec.EnvEntry
	9,  // 1: marshal.v1.AppSpec.logs:type_name -> marshal.v1.LogRetention
	3,  // 2: marshal.v1.StartRequest.apps:type_name -> marshal.v1.AppSpec
	6,  // 3: marshal.v1.ProcList.procs:type_name -> marshal.v1.ProcInfo
	0,  // 4: marshal.v1.LogRequest.stream:type_name -> marshal.v1.LogStream
	12, // 5: marshal.v1.MetricsHistoryResponse.buckets:type_name -> marshal.v1.MetricBucket
	4,  // 6: marshal.v1.Daemon.Start:input_type -> marshal.v1.StartRequest
	5,  // 7: marshal.v1.Daemon.Stop:input_type -> marshal.v1.Selector
	5,  // 8: marshal.v1.Daemon.Restart:input_type -> marshal.v1.Selector
	5,  // 9: marshal.v1.Daemon.Delete:input_type -> marshal.v1.Selector
	1,  // 10: marshal.v1.Daemon.List:input_type -> marshal.v1.Empty
	5,  // 11: marshal.v1.Daemon.Describe:input_type -> marshal.v1.Selector
	1,  // 12: marshal.v1.Daemon.Save:input_type -> marshal.v1.Empty
	1,  // 13: marshal.v1.Daemon.Resurrect:input_type -> marshal.v1.Empty
	1,  // 14: marshal.v1.Daemon.Kill:input_type -> marshal.v1.Empty
	8,  // 15: marshal.v1.Daemon.Logs:input_type -> marshal.v1.LogRequest
	11, // 16: marshal.v1.Daemon.MetricsHistory:input_type -> marshal.v1.MetricsHistoryRequest
	7,  // 17: marshal.v1.Daemon.Start:output_type -> marshal.v1.ProcList
	7,  // 18: marshal.v1.Daemon.Stop:output_type -> marshal.v1.ProcList
	7,  // 19: marshal.v1.Daemon.Restart:output_type -> marshal.v1.ProcList
	7,  // 20: marshal.v1.Daemon.Delete:output_type -> marshal.v1.ProcList
	7,  // 21: marshal.v1.Daemon.List:output_type -> marshal.v1.ProcList
	7,  // 22: marshal.v1.Daemon.Describe:output_type -> marshal.v1.ProcList
	2,  // 23: marshal.v1.Daemon.Save:output_type -> marshal.v1.Ack
	7,  // 24: marshal.v1.Daemon.Resurrect:output_type -> marshal.v1.ProcList
	2,  // 25: marshal.v1.Daemon.Kill:output_type -> marshal.v1.Ack
	10, // 26: marshal.v1.Daemon.Logs:output_type -> marshal.v1.LogLine
	13, // 27: marshal.v1.Daemon.MetricsHistory:output_type -> marshal.v1.MetricsHistoryResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_marshal_v1_daemon_proto_init() }
func file_marshal_v1_daemon_proto_init() {
	if File_marshal_v1_daemon_proto != nil {
		return
	}
	file_marshal_v1_daemon_proto_msgTypes[2].OneofWrappers = []any{}
	file_marshal_v1_daemon_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marshal_v1_daemon_proto_rawDesc), len(file_marshal_v1_daemon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marshal_v1_daemon_proto_goTypes,
		DependencyIndexes: file_marshal_v1_daemon_proto_depIdxs,
		EnumInfos:         file_marshal_v1_daemon_proto_enumTypes,
		MessageInfos:      file_marshal_v1_daemon_proto_msgTypes,
	}.Build()
	File_marshal_v1_daemon_proto = out.File
	file_marshal_v1_daemon_proto_goTypes = nil
	file_marshal_v1_daemon_proto_depIdxs = nil
}
