// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: marshal/v1/fleet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fleet_Connect_FullMethodName   = "/marshal.v1.Fleet/Connect"
	Fleet_ListFleet_FullMethodName = "/marshal.v1.Fleet/ListFleet"
)

// FleetClient is the client API for Fleet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Fleet is the agent<->server control surface (M7: connection + live state).
type FleetClient interface {
	// Agent-initiated, long-lived, bidirectional. M7 uses only the upstream direction.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
	// Read path for the fleet CLI (and, later, the dashboard).
	ListFleet(ctx context.Context, in *ListFleetRequest, opts ...grpc.CallOption) (*ListFleetResponse, error)
}

type fleetClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetClient(cc grpc.ClientConnInterface) FleetClient {
	return &fleetClient{cc}
}

func (c *fleetClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Fleet_ServiceDesc.Streams[0], Fleet_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fleet_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

func (c *fleetClient) ListFleet(ctx context.Context, in *ListFleetRequest, opts ...grpc.CallOption) (*ListFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFleetResponse)
	err := c.cc.Invoke(ctx, Fleet_ListFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServer is the server API for Fleet service.
// All implementations must embed UnimplementedFleetServer
// for forward compatibility.
//
// Fleet is the agent<->server control surface (M7: connection + live state).
type FleetServer interface {
	// Agent-initiated, long-lived, bidirectional. M7 uses only the upstream direction.
	Connect(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	// Read path for the fleet CLI (and, later, the dashboard).
	ListFleet(context.Context, *ListFleetRequest) (*ListFleetResponse, error)
	mustEmbedUnimplementedFleetServer()
}

// UnimplementedFleetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServer struct{}

func (UnimplementedFleetServer) Connect(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedFleetServer) ListFleet(context.Context, *ListFleetRequest) (*ListFleetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFleet not implemented")
}
func (UnimplementedFleetServer) mustEmbedUnimplementedFleetServer() {}
func (UnimplementedFleetServer) testEmbeddedByValue()               {}

// UnsafeFleetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServer will
// result in compilation errors.
type UnsafeFleetServer interface {
	mustEmbedUnimplementedFleetServer()
}

func RegisterFleetServer(s grpc.ServiceRegistrar, srv FleetServer) {
	// If the following call panics, it indicates UnimplementedFleetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fleet_ServiceDesc, srv)
}

func _Fleet_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetServer).Connect(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fleet_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

func _Fleet_ListFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServer).ListFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fleet_ListFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServer).ListFleet(ctx, req.(*ListFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fleet_ServiceDesc is the grpc.ServiceDesc for Fleet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fleet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marshal.v1.Fleet",
	HandlerType: (*FleetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFleet",
			Handler:    _Fleet_ListFleet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Fleet_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "marshal/v1/fleet.proto",
}
