// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: marshal/v1/fleet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialKind int32

const (
	CredentialKind_CRED_HTTPS CredentialKind = 0
	CredentialKind_CRED_SSH   CredentialKind = 1
)

// Enum value maps for CredentialKind.
var (
	CredentialKind_name = map[int32]string{
		0: "CRED_HTTPS",
		1: "CRED_SSH",
	}
	CredentialKind_value = map[string]int32{
		"CRED_HTTPS": 0,
		"CRED_SSH":   1,
	}
)

func (x CredentialKind) Enum() *CredentialKind {
	p := new(CredentialKind)
	*p = x
	return p
}

func (x CredentialKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialKind) Descriptor() protoreflect.EnumDescriptor {
	return file_marshal_v1_fleet_proto_enumTypes[0].Descriptor()
}

func (CredentialKind) Type() protoreflect.EnumType {
	return &file_marshal_v1_fleet_proto_enumTypes[0]
}

func (x CredentialKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialKind.Descriptor instead.
func (CredentialKind) EnumDescriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{0}
}

type CommitKind int32

const (
	CommitKind_COMMIT_EDIT   CommitKind = 0
	CommitKind_COMMIT_CREATE CommitKind = 1
	CommitKind_COMMIT_DELETE CommitKind = 2
	CommitKind_COMMIT_RENAME CommitKind = 3
)

// Enum value maps for CommitKind.
var (
	CommitKind_name = map[int32]string{
		0: "COMMIT_EDIT",
		1: "COMMIT_CREATE",
		2: "COMMIT_DELETE",
		3: "COMMIT_RENAME",
	}
	CommitKind_value = map[string]int32{
		"COMMIT_EDIT":   0,
		"COMMIT_CREATE": 1,
		"COMMIT_DELETE": 2,
		"COMMIT_RENAME": 3,
	}
)

func (x CommitKind) Enum() *CommitKind {
	p := new(CommitKind)
	*p = x
	return p
}

func (x CommitKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommitKind) Descriptor() protoreflect.EnumDescriptor {
	return file_marshal_v1_fleet_proto_enumTypes[1].Descriptor()
}

func (CommitKind) Type() protoreflect.EnumType {
	return &file_marshal_v1_fleet_proto_enumTypes[1]
}

func (x CommitKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommitKind.Descriptor instead.
func (CommitKind) EnumDescriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{1}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Snapshot
	//	*AgentMessage_Metrics
	//	*AgentMessage_Logs
	//	*AgentMessage_Result
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetSnapshot() *StateSnapshot {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *MetricBatch {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetLogs() *LogBatch {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // sent once on connect
}

type AgentMessage_Snapshot struct {
	Snapshot *StateSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"` // full process-state snapshot (periodic)
}

type AgentMessage_Metrics struct {
	Metrics *MetricBatch `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"` // raw CPU/mem samples (M8)
}

type AgentMessage_Logs struct {
	Logs *LogBatch `protobuf:"bytes,4,opt,name=logs,proto3,oneof"` // captured stdout/stderr lines (M8b)
}

type AgentMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,5,opt,name=result,proto3,oneof"` // M9: result of a routed command
}

func (*AgentMessage_Hello) isAgentMessage_Msg() {}

func (*AgentMessage_Snapshot) isAgentMessage_Msg() {}

func (*AgentMessage_Metrics) isAgentMessage_Msg() {}

func (*AgentMessage_Logs) isAgentMessage_Msg() {}

func (*AgentMessage_Result) isAgentMessage_Msg() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_HelloAck
	//	*ServerMessage_Command
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ServerMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerMessage_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"` // M9: control command routed down to the agent
}

func (*ServerMessage_HelloAck) isServerMessage_Msg() {}

func (*ServerMessage_Command) isServerMessage_Msg() {}

type Hello struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentName      string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	MarshalVersion string                 `protobuf:"bytes,2,opt,name=marshal_version,json=marshalVersion,proto3" json:"marshal_version,omitempty"`
	Hostname       string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`                                // os.Hostname()
	Os             string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                            // runtime.GOOS
	Arch           string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`                                        // runtime.GOARCH
	HostBootUnix   int64                  `protobuf:"varint,6,opt,name=host_boot_unix,json=hostBootUnix,proto3" json:"host_boot_unix,omitempty"` // host boot time; uptime = now - boot
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *Hello) GetMarshalVersion() string {
	if x != nil {
		return x.MarshalVersion
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetHostBootUnix() int64 {
	if x != nil {
		return x.HostBootUnix
	}
	return 0
}

type HelloAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LastMetricTsMs int64                  `protobuf:"varint,1,opt,name=last_metric_ts_ms,json=lastMetricTsMs,proto3" json:"last_metric_ts_ms,omitempty"` // server's stored high-water-mark for this agent (0 = none)
	LastLogTsMs    int64                  `protobuf:"varint,2,opt,name=last_log_ts_ms,json=lastLogTsMs,proto3" json:"last_log_ts_ms,omitempty"`          // server's stored log high-water-mark (0 = none)
	AgentToken     string                 `protobuf:"bytes,3,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`                  // M10: minted per-agent token (set only on enrollment)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetLastMetricTsMs() int64 {
	if x != nil {
		return x.LastMetricTsMs
	}
	return 0
}

func (x *HelloAck) GetLastLogTsMs() int64 {
	if x != nil {
		return x.LastLogTsMs
	}
	return 0
}

func (x *HelloAck) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

// HostMetrics — M-C: current-value host gauges (point-in-time, per agent).
type HostMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"` // aggregate host CPU utilization %
	Load1         float64                `protobuf:"fixed64,2,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5         float64                `protobuf:"fixed64,3,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15        float64                `protobuf:"fixed64,4,opt,name=load15,proto3" json:"load15,omitempty"`
	MemTotal      uint64                 `protobuf:"varint,5,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"` // bytes
	MemUsed       uint64                 `protobuf:"varint,6,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`    // bytes
	MemUsedPct    float64                `protobuf:"fixed64,7,opt,name=mem_used_pct,json=memUsedPct,proto3" json:"mem_used_pct,omitempty"`
	NetRxBps      float64                `protobuf:"fixed64,8,opt,name=net_rx_bps,json=netRxBps,proto3" json:"net_rx_bps,omitempty"` // bytes/sec received (rate)
	NetTxBps      float64                `protobuf:"fixed64,9,opt,name=net_tx_bps,json=netTxBps,proto3" json:"net_tx_bps,omitempty"` // bytes/sec sent (rate)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *HostMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HostMetrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *HostMetrics) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *HostMetrics) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *HostMetrics) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *HostMetrics) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *HostMetrics) GetMemUsedPct() float64 {
	if x != nil {
		return x.MemUsedPct
	}
	return 0
}

func (x *HostMetrics) GetNetRxBps() float64 {
	if x != nil {
		return x.NetRxBps
	}
	return 0
}

func (x *HostMetrics) GetNetTxBps() float64 {
	if x != nil {
		return x.NetTxBps
	}
	return 0
}

type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Procs         []*ProcInfo            `protobuf:"bytes,1,rep,name=procs,proto3" json:"procs,omitempty"` // ProcInfo from daemon.proto
	Host          *HostMetrics           `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`   // M-C: current host gauges (nil if none)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *StateSnapshot) GetProcs() []*ProcInfo {
	if x != nil {
		return x.Procs
	}
	return nil
}

func (x *StateSnapshot) GetHost() *HostMetrics {
	if x != nil {
		return x.Host
	}
	return nil
}

type ListFleetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFleetRequest) Reset() {
	*x = ListFleetRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFleetRequest) ProtoMessage() {}

func (x *ListFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFleetRequest.ProtoReflect.Descriptor instead.
func (*ListFleetRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{6}
}

type ListFleetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentState          `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFleetResponse) Reset() {
	*x = ListFleetResponse{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFleetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFleetResponse) ProtoMessage() {}

func (x *ListFleetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFleetResponse.ProtoReflect.Descriptor instead.
func (*ListFleetResponse) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *ListFleetResponse) GetAgents() []*AgentState {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentName      string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Connected      bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	LastSeenUnix   int64                  `protobuf:"varint,3,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	Procs          []*ProcInfo            `protobuf:"bytes,4,rep,name=procs,proto3" json:"procs,omitempty"`
	Hostname       string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip             string                 `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"` // server-derived from the gRPC peer
	Os             string                 `protobuf:"bytes,7,opt,name=os,proto3" json:"os,omitempty"`
	Arch           string                 `protobuf:"bytes,8,opt,name=arch,proto3" json:"arch,omitempty"`
	MarshalVersion string                 `protobuf:"bytes,9,opt,name=marshal_version,json=marshalVersion,proto3" json:"marshal_version,omitempty"`
	HostBootUnix   int64                  `protobuf:"varint,10,opt,name=host_boot_unix,json=hostBootUnix,proto3" json:"host_boot_unix,omitempty"`
	Host           *HostMetrics           `protobuf:"bytes,11,opt,name=host,proto3" json:"host,omitempty"` // M-C: latest host gauges
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *AgentState) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentState) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *AgentState) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *AgentState) GetProcs() []*ProcInfo {
	if x != nil {
		return x.Procs
	}
	return nil
}

func (x *AgentState) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentState) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentState) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentState) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentState) GetMarshalVersion() string {
	if x != nil {
		return x.MarshalVersion
	}
	return ""
}

func (x *AgentState) GetHostBootUnix() int64 {
	if x != nil {
		return x.HostBootUnix
	}
	return 0
}

func (x *AgentState) GetHost() *HostMetrics {
	if x != nil {
		return x.Host
	}
	return nil
}

// One stored metric row, flattened to map 1:1 to a metricstore row.
type MetricSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // "app#instance"
	Cpu           float64                `protobuf:"fixed64,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem           int64                  `protobuf:"varint,4,opt,name=mem,proto3" json:"mem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *MetricSample) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *MetricSample) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MetricSample) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *MetricSample) GetMem() int64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*MetricSample        `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *MetricBatch) GetSamples() []*MetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

// One captured log line, flattened to map 1:1 to a logstore row.
type LogShipLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // "app#instance"
	Stderr        bool                   `protobuf:"varint,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogShipLine) Reset() {
	*x = LogShipLine{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogShipLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogShipLine) ProtoMessage() {}

func (x *LogShipLine) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogShipLine.ProtoReflect.Descriptor instead.
func (*LogShipLine) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{11}
}

func (x *LogShipLine) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *LogShipLine) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LogShipLine) GetStderr() bool {
	if x != nil {
		return x.Stderr
	}
	return false
}

func (x *LogShipLine) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*LogShipLine         `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{12}
}

func (x *LogBatch) GetLines() []*LogShipLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type FleetLogsHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`                        // app name or "name#instance" label
	Lines         int32                  `protobuf:"varint,3,opt,name=lines,proto3" json:"lines,omitempty"`                             // backfill count
	Stream        LogStream              `protobuf:"varint,4,opt,name=stream,proto3,enum=marshal.v1.LogStream" json:"stream,omitempty"` // reuse daemon.proto enum; unspecified = merged
	Grep          string                 `protobuf:"bytes,5,opt,name=grep,proto3" json:"grep,omitempty"`                                // only lines containing this substring (case-insensitive); empty = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetLogsHistoryRequest) Reset() {
	*x = FleetLogsHistoryRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetLogsHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetLogsHistoryRequest) ProtoMessage() {}

func (x *FleetLogsHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetLogsHistoryRequest.ProtoReflect.Descriptor instead.
func (*FleetLogsHistoryRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{13}
}

func (x *FleetLogsHistoryRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *FleetLogsHistoryRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *FleetLogsHistoryRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *FleetLogsHistoryRequest) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

func (x *FleetLogsHistoryRequest) GetGrep() string {
	if x != nil {
		return x.Grep
	}
	return ""
}

type FleetLogsHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*LogLine             `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetLogsHistoryResponse) Reset() {
	*x = FleetLogsHistoryResponse{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetLogsHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetLogsHistoryResponse) ProtoMessage() {}

func (x *FleetLogsHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetLogsHistoryResponse.ProtoReflect.Descriptor instead.
func (*FleetLogsHistoryResponse) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{14}
}

func (x *FleetLogsHistoryResponse) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type FleetMetricsHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"` // app name or "name#instance" label
	SinceMs       int64                  `protobuf:"varint,3,opt,name=since_ms,json=sinceMs,proto3" json:"since_ms,omitempty"`
	BucketMs      int64                  `protobuf:"varint,4,opt,name=bucket_ms,json=bucketMs,proto3" json:"bucket_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetMetricsHistoryRequest) Reset() {
	*x = FleetMetricsHistoryRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMetricsHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMetricsHistoryRequest) ProtoMessage() {}

func (x *FleetMetricsHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMetricsHistoryRequest.ProtoReflect.Descriptor instead.
func (*FleetMetricsHistoryRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{15}
}

func (x *FleetMetricsHistoryRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *FleetMetricsHistoryRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *FleetMetricsHistoryRequest) GetSinceMs() int64 {
	if x != nil {
		return x.SinceMs
	}
	return 0
}

func (x *FleetMetricsHistoryRequest) GetBucketMs() int64 {
	if x != nil {
		return x.BucketMs
	}
	return 0
}

type GitCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                               // HTTPS only
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`   // SSH only — sealed in transit by TLS; never persisted on the agent
	KnownHosts    string                 `protobuf:"bytes,4,opt,name=known_hosts,json=knownHosts,proto3" json:"known_hosts,omitempty"`   // SSH only — the server-pinned host key line(s)
	Kind          CredentialKind         `protobuf:"varint,5,opt,name=kind,proto3,enum=marshal.v1.CredentialKind" json:"kind,omitempty"` // default CRED_HTTPS keeps M22/M24 agents working
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitCredential) Reset() {
	*x = GitCredential{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitCredential) ProtoMessage() {}

func (x *GitCredential) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitCredential.ProtoReflect.Descriptor instead.
func (*GitCredential) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{16}
}

func (x *GitCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GitCredential) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GitCredential) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *GitCredential) GetKnownHosts() string {
	if x != nil {
		return x.KnownHosts
	}
	return ""
}

func (x *GitCredential) GetKind() CredentialKind {
	if x != nil {
		return x.Kind
	}
	return CredentialKind_CRED_HTTPS
}

// M23 — read-only file browser for deployed apps.
type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{17}
}

func (x *ListDirRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{18}
}

func (x *ReadFileRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModUnix       int64                  `protobuf:"varint,4,opt,name=mod_unix,json=modUnix,proto3" json:"mod_unix,omitempty"`
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"` // unix perm bits, for display
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{19}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DirEntry) GetModUnix() int64 {
	if x != nil {
		return x.ModUnix
	}
	return 0
}

func (x *DirEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type DirListing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Entries       []*DirEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirListing) Reset() {
	*x = DirListing{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirListing) ProtoMessage() {}

func (x *DirListing) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirListing.ProtoReflect.Descriptor instead.
func (*DirListing) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{20}
}

func (x *DirListing) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirListing) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`           // true on-disk size (may exceed len(content) when truncated/binary)
	Truncated     bool                   `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"` // content is a head, capped at maxFileBytes
	Binary        bool                   `protobuf:"varint,5,opt,name=binary,proto3" json:"binary,omitempty"`       // NUL-byte sniff: not rendered as text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{21}
}

func (x *FileContent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileContent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileContent) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *FileContent) GetBinary() bool {
	if x != nil {
		return x.Binary
	}
	return false
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *AppSpec               `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Credential    *GitCredential         `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"` // M22: secret attached per-op, never persisted on the agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{22}
}

func (x *DeployRequest) GetApp() *AppSpec {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *DeployRequest) GetCredential() *GitCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type RedeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`         // M21 app name
	Credential    *GitCredential         `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"` // M22
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeployRequest) Reset() {
	*x = RedeployRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeployRequest) ProtoMessage() {}

func (x *RedeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeployRequest.ProtoReflect.Descriptor instead.
func (*RedeployRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{23}
}

func (x *RedeployRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RedeployRequest) GetCredential() *GitCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

// M24 — a single file mutation (edit/create/delete/rename) committed and pushed.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Kind          CommitKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=marshal.v1.CommitKind" json:"kind,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                      // target (edit/create/delete) or rename source
	NewPath       string                 `protobuf:"bytes,4,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"` // rename destination only
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                // edit/create only
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                // commit message (server fills a default)
	Credential    *GitCredential         `protobuf:"bytes,7,opt,name=credential,proto3" json:"credential,omitempty"`          // M22 secret, attached per-op, never persisted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{24}
}

func (x *CommitRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *CommitRequest) GetKind() CommitKind {
	if x != nil {
		return x.Kind
	}
	return CommitKind_COMMIT_EDIT
}

func (x *CommitRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CommitRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

func (x *CommitRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CommitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitRequest) GetCredential() *GitCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type CommitResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha           string                 `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResult) Reset() {
	*x = CommitResult{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResult) ProtoMessage() {}

func (x *CommitResult) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResult.ProtoReflect.Descriptor instead.
func (*CommitResult) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{25}
}

func (x *CommitResult) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *CommitResult) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

// M9 — control-plane command surface, shared by the down-stream Command and the
// CLI's unary FleetControl so the op/result shapes have one definition.
type ControlOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*ControlOp_Stop
	//	*ControlOp_Restart
	//	*ControlOp_Delete
	//	*ControlOp_Start
	//	*ControlOp_Deploy
	//	*ControlOp_Redeploy
	//	*ControlOp_ListDir
	//	*ControlOp_ReadFile
	//	*ControlOp_Commit
	//	*ControlOp_Reload
	//	*ControlOp_Reset_
	//	*ControlOp_Flush
	Op            isControlOp_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlOp) Reset() {
	*x = ControlOp{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlOp) ProtoMessage() {}

func (x *ControlOp) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlOp.ProtoReflect.Descriptor instead.
func (*ControlOp) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{26}
}

func (x *ControlOp) GetOp() isControlOp_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *ControlOp) GetStop() *Selector {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *ControlOp) GetRestart() *Selector {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *ControlOp) GetDelete() *Selector {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *ControlOp) GetStart() *StartRequest {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ControlOp) GetDeploy() *DeployRequest {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Deploy); ok {
			return x.Deploy
		}
	}
	return nil
}

func (x *ControlOp) GetRedeploy() *RedeployRequest {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Redeploy); ok {
			return x.Redeploy
		}
	}
	return nil
}

func (x *ControlOp) GetListDir() *ListDirRequest {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_ListDir); ok {
			return x.ListDir
		}
	}
	return nil
}

func (x *ControlOp) GetReadFile() *ReadFileRequest {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_ReadFile); ok {
			return x.ReadFile
		}
	}
	return nil
}

func (x *ControlOp) GetCommit() *CommitRequest {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *ControlOp) GetReload() *Selector {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Reload); ok {
			return x.Reload
		}
	}
	return nil
}

func (x *ControlOp) GetReset_() *Selector {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *ControlOp) GetFlush() *Selector {
	if x != nil {
		if x, ok := x.Op.(*ControlOp_Flush); ok {
			return x.Flush
		}
	}
	return nil
}

type isControlOp_Op interface {
	isControlOp_Op()
}

type ControlOp_Stop struct {
	Stop *Selector `protobuf:"bytes,1,opt,name=stop,proto3,oneof"`
}

type ControlOp_Restart struct {
	Restart *Selector `protobuf:"bytes,2,opt,name=restart,proto3,oneof"`
}

type ControlOp_Delete struct {
	Delete *Selector `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type ControlOp_Start struct {
	Start *StartRequest `protobuf:"bytes,4,opt,name=start,proto3,oneof"` // reuses AppSpec from daemon.proto
}

type ControlOp_Deploy struct {
	Deploy *DeployRequest `protobuf:"bytes,5,opt,name=deploy,proto3,oneof"` // M21
}

type ControlOp_Redeploy struct {
	Redeploy *RedeployRequest `protobuf:"bytes,6,opt,name=redeploy,proto3,oneof"` // M21
}

type ControlOp_ListDir struct {
	ListDir *ListDirRequest `protobuf:"bytes,7,opt,name=list_dir,json=listDir,proto3,oneof"` // M23
}

type ControlOp_ReadFile struct {
	ReadFile *ReadFileRequest `protobuf:"bytes,8,opt,name=read_file,json=readFile,proto3,oneof"` // M23
}

type ControlOp_Commit struct {
	Commit *CommitRequest `protobuf:"bytes,9,opt,name=commit,proto3,oneof"` // M24
}

type ControlOp_Reload struct {
	Reload *Selector `protobuf:"bytes,10,opt,name=reload,proto3,oneof"` // M-G, rolling graceful restart
}

type ControlOp_Reset_ struct {
	Reset_ *Selector `protobuf:"bytes,11,opt,name=reset,proto3,oneof"` // zero restart counters
}

type ControlOp_Flush struct {
	Flush *Selector `protobuf:"bytes,12,opt,name=flush,proto3,oneof"` // clear logs
}

func (*ControlOp_Stop) isControlOp_Op() {}

func (*ControlOp_Restart) isControlOp_Op() {}

func (*ControlOp_Delete) isControlOp_Op() {}

func (*ControlOp_Start) isControlOp_Op() {}

func (*ControlOp_Deploy) isControlOp_Op() {}

func (*ControlOp_Redeploy) isControlOp_Op() {}

func (*ControlOp_ListDir) isControlOp_Op() {}

func (*ControlOp_ReadFile) isControlOp_Op() {}

func (*ControlOp_Commit) isControlOp_Op() {}

func (*ControlOp_Reload) isControlOp_Op() {}

func (*ControlOp_Reset_) isControlOp_Op() {}

func (*ControlOp_Flush) isControlOp_Op() {}

type ControlResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`   // set when ok == false
	Procs         []*ProcInfo            `protobuf:"bytes,3,rep,name=procs,proto3" json:"procs,omitempty"`   // affected instances on success
	Dir           *DirListing            `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty"`       // M23, set on list_dir success
	File          *FileContent           `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`     // M23, set on read_file success
	Commit        *CommitResult          `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"` // M24, set on commit success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResult) Reset() {
	*x = ControlResult{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResult) ProtoMessage() {}

func (x *ControlResult) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResult.ProtoReflect.Descriptor instead.
func (*ControlResult) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{27}
}

func (x *ControlResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ControlResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ControlResult) GetProcs() []*ProcInfo {
	if x != nil {
		return x.Procs
	}
	return nil
}

func (x *ControlResult) GetDir() *DirListing {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *ControlResult) GetFile() *FileContent {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ControlResult) GetCommit() *CommitResult {
	if x != nil {
		return x.Commit
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Op            *ControlOp             `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{28}
}

func (x *Command) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Command) GetOp() *ControlOp {
	if x != nil {
		return x.Op
	}
	return nil
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Result        *ControlResult         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{29}
}

func (x *CommandResult) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CommandResult) GetResult() *ControlResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type FleetControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Op            *ControlOp             `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetControlRequest) Reset() {
	*x = FleetControlRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetControlRequest) ProtoMessage() {}

func (x *FleetControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetControlRequest.ProtoReflect.Descriptor instead.
func (*FleetControlRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{30}
}

func (x *FleetControlRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *FleetControlRequest) GetOp() *ControlOp {
	if x != nil {
		return x.Op
	}
	return nil
}

type FleetControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ControlResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetControlResponse) Reset() {
	*x = FleetControlResponse{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetControlResponse) ProtoMessage() {}

func (x *FleetControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetControlResponse.ProtoReflect.Descriptor instead.
func (*FleetControlResponse) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{31}
}

func (x *FleetControlResponse) GetResult() *ControlResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_marshal_v1_fleet_proto protoreflect.FileDescriptor

const file_marshal_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"\x16marshal/v1/fleet.proto\x12\n" +
	"marshal.v1\x1a\x17marshal/v1/daemon.proto\"\x8f\x02\n" +
	"\fAgentMessage\x12)\n" +
	"\x05hello\x18\x01 \x01(\v2\x11.marshal.v1.HelloH\x00R\x05hello\x127\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.marshal.v1.StateSnapshotH\x00R\bsnapshot\x123\n" +
	"\ametrics\x18\x03 \x01(\v2\x17.marshal.v1.MetricBatchH\x00R\ametrics\x12*\n" +
	"\x04logs\x18\x04 \x01(\v2\x14.marshal.v1.LogBatchH\x00R\x04logs\x123\n" +
	"\x06result\x18\x05 \x01(\v2\x19.marshal.v1.CommandResultH\x00R\x06resultB\x05\n" +
	"\x03msg\"|\n" +
	"\rServerMessage\x123\n" +
	"\thello_ack\x18\x01 \x01(\v2\x14.marshal.v1.HelloAckH\x00R\bhelloAck\x12/\n" +
	"\acommand\x18\x02 \x01(\v2\x13.marshal.v1.CommandH\x00R\acommandB\x05\n" +
	"\x03msg\"\xb5\x01\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12'\n" +
	"\x0fmarshal_version\x18\x02 \x01(\tR\x0emarshalVersion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12$\n" +
	"\x0ehost_boot_unix\x18\x06 \x01(\x03R\fhostBootUnix\"{\n" +
	"\bHelloAck\x12)\n" +
	"\x11last_metric_ts_ms\x18\x01 \x01(\x03R\x0elastMetricTsMs\x12#\n" +
	"\x0elast_log_ts_ms\x18\x02 \x01(\x03R\vlastLogTsMs\x12\x1f\n" +
	"\vagent_token\x18\x03 \x01(\tR\n" +
	"agentToken\"\x88\x02\n" +
	"\vHostMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x14\n" +
	"\x05load1\x18\x02 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\x03 \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\x04 \x01(\x01R\x06load15\x12\x1b\n" +
	"\tmem_total\x18\x05 \x01(\x04R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\x06 \x01(\x04R\amemUsed\x12 \n" +
	"\fmem_used_pct\x18\a \x01(\x01R\n" +
	"memUsedPct\x12\x1c\n" +
	"\n" +
	"net_rx_bps\x18\b \x01(\x01R\bnetRxBps\x12\x1c\n" +
	"\n" +
	"net_tx_bps\x18\t \x01(\x01R\bnetTxBps\"h\n" +
	"\rStateSnapshot\x12*\n" +
	"\x05procs\x18\x01 \x03(\v2\x14.marshal.v1.ProcInfoR\x05procs\x12+\n" +
	"\x04host\x18\x02 \x01(\v2\x17.marshal.v1.HostMetricsR\x04host\"\x12\n" +
	"\x10ListFleetRequest\"C\n" +
	"\x11ListFleetResponse\x12.\n" +
	"\x06agents\x18\x01 \x03(\v2\x16.marshal.v1.AgentStateR\x06agents\"\xe7\x02\n" +
	"\n" +
	"AgentState\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12$\n" +
	"\x0elast_seen_unix\x18\x03 \x01(\x03R\flastSeenUnix\x12*\n" +
	"\x05procs\x18\x04 \x03(\v2\x14.marshal.v1.ProcInfoR\x05procs\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02os\x18\a \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\b \x01(\tR\x04arch\x12'\n" +
	"\x0fmarshal_version\x18\t \x01(\tR\x0emarshalVersion\x12$\n" +
	"\x0ehost_boot_unix\x18\n" +
	" \x01(\x03R\fhostBootUnix\x12+\n" +
	"\x04host\x18\v \x01(\v2\x17.marshal.v1.HostMetricsR\x04host\"]\n" +
	"\fMetricSample\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x04 \x01(\x03R\x03mem\"A\n" +
	"\vMetricBatch\x122\n" +
	"\asamples\x18\x01 \x03(\v2\x18.marshal.v1.MetricSampleR\asamples\"d\n" +
	"\vLogShipLine\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\bR\x06stderr\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"9\n" +
	"\bLogBatch\x12-\n" +
	"\x05lines\x18\x01 \x03(\v2\x17.marshal.v1.LogShipLineR\x05lines\"\xad\x01\n" +
	"\x17FleetLogsHistoryRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x14\n" +
	"\x05lines\x18\x03 \x01(\x05R\x05lines\x12-\n" +
	"\x06stream\x18\x04 \x01(\x0e2\x15.marshal.v1.LogStreamR\x06stream\x12\x12\n" +
	"\x04grep\x18\x05 \x01(\tR\x04grep\"E\n" +
	"\x18FleetLogsHistoryResponse\x12)\n" +
	"\x05lines\x18\x01 \x03(\v2\x13.marshal.v1.LogLineR\x05lines\"\x8f\x01\n" +
	"\x1aFleetMetricsHistoryRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x19\n" +
	"\bsince_ms\x18\x03 \x01(\x03R\asinceMs\x12\x1b\n" +
	"\tbucket_ms\x18\x04 \x01(\x03R\bbucketMs\"\xb3\x01\n" +
	"\rGitCredential\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x1f\n" +
	"\vknown_hosts\x18\x04 \x01(\tR\n" +
	"knownHosts\x12.\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x1a.marshal.v1.CredentialKindR\x04kind\"6\n" +
	"\x0eListDirRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"7\n" +
	"\x0fReadFileRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"x\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_unix\x18\x04 \x01(\x03R\amodUnix\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\"P\n" +
	"\n" +
	"DirListing\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12.\n" +
	"\aentries\x18\x02 \x03(\v2\x14.marshal.v1.DirEntryR\aentries\"\x85\x01\n" +
	"\vFileContent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncated\x12\x16\n" +
	"\x06binary\x18\x05 \x01(\bR\x06binary\"q\n" +
	"\rDeployRequest\x12%\n" +
	"\x03app\x18\x01 \x01(\v2\x13.marshal.v1.AppSpecR\x03app\x129\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2\x19.marshal.v1.GitCredentialR\n" +
	"credential\"d\n" +
	"\x0fRedeployRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x129\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2\x19.marshal.v1.GitCredentialR\n" +
	"credential\"\xeb\x01\n" +
	"\rCommitRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.marshal.v1.CommitKindR\x04kind\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x19\n" +
	"\bnew_path\x18\x04 \x01(\tR\anewPath\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x129\n" +
	"\n" +
	"credential\x18\a \x01(\v2\x19.marshal.v1.GitCredentialR\n" +
	"credential\"8\n" +
	"\fCommitResult\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\"\xf7\x04\n" +
	"\tControlOp\x12*\n" +
	"\x04stop\x18\x01 \x01(\v2\x14.marshal.v1.SelectorH\x00R\x04stop\x120\n" +
	"\arestart\x18\x02 \x01(\v2\x14.marshal.v1.SelectorH\x00R\arestart\x12.\n" +
	"\x06delete\x18\x03 \x01(\v2\x14.marshal.v1.SelectorH\x00R\x06delete\x120\n" +
	"\x05start\x18\x04 \x01(\v2\x18.marshal.v1.StartRequestH\x00R\x05start\x123\n" +
	"\x06deploy\x18\x05 \x01(\v2\x19.marshal.v1.DeployRequestH\x00R\x06deploy\x129\n" +
	"\bredeploy\x18\x06 \x01(\v2\x1b.marshal.v1.RedeployRequestH\x00R\bredeploy\x127\n" +
	"\blist_dir\x18\a \x01(\v2\x1a.marshal.v1.ListDirRequestH\x00R\alistDir\x12:\n" +
	"\tread_file\x18\b \x01(\v2\x1b.marshal.v1.ReadFileRequestH\x00R\breadFile\x123\n" +
	"\x06commit\x18\t \x01(\v2\x19.marshal.v1.CommitRequestH\x00R\x06commit\x12.\n" +
	"\x06reload\x18\n" +
	" \x01(\v2\x14.marshal.v1.SelectorH\x00R\x06reload\x12,\n" +
	"\x05reset\x18\v \x01(\v2\x14.marshal.v1.SelectorH\x00R\x05reset\x12,\n" +
	"\x05flush\x18\f \x01(\v2\x14.marshal.v1.SelectorH\x00R\x05flushB\x04\n" +
	"\x02op\"\xea\x01\n" +
	"\rControlResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12*\n" +
	"\x05procs\x18\x03 \x03(\v2\x14.marshal.v1.ProcInfoR\x05procs\x12(\n" +
	"\x03dir\x18\x04 \x01(\v2\x16.marshal.v1.DirListingR\x03dir\x12+\n" +
	"\x04file\x18\x05 \x01(\v2\x17.marshal.v1.FileContentR\x04file\x120\n" +
	"\x06commit\x18\x06 \x01(\v2\x18.marshal.v1.CommitResultR\x06commit\"O\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12%\n" +
	"\x02op\x18\x02 \x01(\v2\x15.marshal.v1.ControlOpR\x02op\"a\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x121\n" +
	"\x06result\x18\x02 \x01(\v2\x19.marshal.v1.ControlResultR\x06result\"[\n" +
	"\x13FleetControlRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12%\n" +
	"\x02op\x18\x02 \x01(\v2\x15.marshal.v1.ControlOpR\x02op\"I\n" +
	"\x14FleetControlResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.marshal.v1.ControlResultR\x06result*.\n" +
	"\x0eCredentialKind\x12\x0e\n" +
	"\n" +
	"CRED_HTTPS\x10\x00\x12\f\n" +
	"\bCRED_SSH\x10\x01*V\n" +
	"\n" +
	"CommitKind\x12\x0f\n" +
	"\vCOMMIT_EDIT\x10\x00\x12\x11\n" +
	"\rCOMMIT_CREATE\x10\x01\x12\x11\n" +
	"\rCOMMIT_DELETE\x10\x02\x12\x11\n" +
	"\rCOMMIT_RENAME\x10\x032\xaa\x03\n" +
	"\x05Fleet\x12B\n" +
	"\aConnect\x12\x18.marshal.v1.AgentMessage\x1a\x19.marshal.v1.ServerMessage(\x010\x01\x12H\n" +
	"\tListFleet\x12\x1c.marshal.v1.ListFleetRequest\x1a\x1d.marshal.v1.ListFleetResponse\x12a\n" +
	"\x13FleetMetricsHistory\x12&.marshal.v1.FleetMetricsHistoryRequest\x1a\".marshal.v1.MetricsHistoryResponse\x12]\n" +
	"\x10FleetLogsHistory\x12#.marshal.v1.FleetLogsHistoryRequest\x1a$.marshal.v1.FleetLogsHistoryResponse\x12Q\n" +
	"\fFleetControl\x12\x1f.marshal.v1.FleetControlRequest\x1a .marshal.v1.FleetControlResponseB\x18Z\x16marshal/internal/pb;pbb\x06proto3"

var (
	file_marshal_v1_fleet_proto_rawDescOnce sync.Once
	file_marshal_v1_fleet_proto_rawDescData []byte
)

func file_marshal_v1_fleet_proto_rawDescGZIP() []byte {
	file_marshal_v1_fleet_proto_rawDescOnce.Do(func() {
		file_marshal_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marshal_v1_fleet_proto_rawDesc), len(file_marshal_v1_fleet_proto_rawDesc)))
	})
	return file_marshal_v1_fleet_proto_rawDescData
}

var file_marshal_v1_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_marshal_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_marshal_v1_fleet_proto_goTypes = []any{
	(CredentialKind)(0),                // 0: marshal.v1.CredentialKind
	(CommitKind)(0),                    // 1: marshal.v1.CommitKind
	(*AgentMessage)(nil),               // 2: marshal.v1.AgentMessage
	(*ServerMessage)(nil),              // 3: marshal.v1.ServerMessage
	(*Hello)(nil),                      // 4: marshal.v1.Hello
	(*HelloAck)(nil),                   // 5: marshal.v1.HelloAck
	(*HostMetrics)(nil),                // 6: marshal.v1.HostMetrics
	(*StateSnapshot)(nil),              // 7: marshal.v1.StateSnapshot
	(*ListFleetRequest)(nil),           // 8: marshal.v1.ListFleetRequest
	(*ListFleetResponse)(nil),          // 9: marshal.v1.ListFleetResponse
	(*AgentState)(nil),                 // 10: marshal.v1.AgentState
	(*MetricSample)(nil),               // 11: marshal.v1.MetricSample
	(*MetricBatch)(nil),                // 12: marshal.v1.MetricBatch
	(*LogShipLine)(nil),                // 13: marshal.v1.LogShipLine
	(*LogBatch)(nil),                   // 14: marshal.v1.LogBatch
	(*FleetLogsHistoryRequest)(nil),    // 15: marshal.v1.FleetLogsHistoryRequest
	(*FleetLogsHistoryResponse)(nil),   // 16: marshal.v1.FleetLogsHistoryResponse
	(*FleetMetricsHistoryRequest)(nil), // 17: marshal.v1.FleetMetricsHistoryRequest
	(*GitCredential)(nil),              // 18: marshal.v1.GitCredential
	(*ListDirRequest)(nil),             // 19: marshal.v1.ListDirRequest
	(*ReadFileRequest)(nil),            // 20: marshal.v1.ReadFileRequest
	(*DirEntry)(nil),                   // 21: marshal.v1.DirEntry
	(*DirListing)(nil),                 // 22: marshal.v1.DirListing
	(*FileContent)(nil),                // 23: marshal.v1.FileContent
	(*DeployRequest)(nil),              // 24: marshal.v1.DeployRequest
	(*RedeployRequest)(nil),            // 25: marshal.v1.RedeployRequest
	(*CommitRequest)(nil),              // 26: marshal.v1.CommitRequest
	(*CommitResult)(nil),               // 27: marshal.v1.CommitResult
	(*ControlOp)(nil),                  // 28: marshal.v1.ControlOp
	(*ControlResult)(nil),              // 29: marshal.v1.ControlResult
	(*Command)(nil),                    // 30: marshal.v1.Command
	(*CommandResult)(nil),              // 31: marshal.v1.CommandResult
	(*FleetControlRequest)(nil),        // 32: marshal.v1.FleetControlRequest
	(*FleetControlResponse)(nil),       // 33: marshal.v1.FleetControlResponse
	(*ProcInfo)(nil),                   // 34: marshal.v1.ProcInfo
	(LogStream)(0),                     // 35: marshal.v1.LogStream
	(*LogLine)(nil),                    // 36: marshal.v1.LogLine
	(*AppSpec)(nil),                    // 37: marshal.v1.AppSpec
	(*Selector)(nil),                   // 38: marshal.v1.Selector
	(*StartRequest)(nil),               // 39: marshal.v1.StartRequest
	(*MetricsHistoryResponse)(nil),     // 40: marshal.v1.MetricsHistoryResponse
}
var file_marshal_v1_fleet_proto_depIdxs = []int32{
	4,  // 0: marshal.v1.AgentMessage.hello:type_name -> marshal.v1.Hello
	7,  // 1: marshal.v1.AgentMessage.snapshot:type_name -> marshal.v1.StateSnapshot
	12, // 2: marshal.v1.AgentMessage.metrics:type_name -> marshal.v1.MetricBatch
	14, // 3: marshal.v1.AgentMessage.logs:type_name -> marshal.v1.LogBatch
	31, // 4: marshal.v1.AgentMessage.result:type_name -> marshal.v1.CommandResult
	5,  // 5: marshal.v1.ServerMessage.hello_ack:type_name -> marshal.v1.HelloAck
	30, // 6: marshal.v1.ServerMessage.command:type_name -> marshal.v1.Command
	34, // 7: marshal.v1.StateSnapshot.procs:type_name -> marshal.v1.ProcInfo
	6,  // 8: marshal.v1.StateSnapshot.host:type_name -> marshal.v1.HostMetrics
	10, // 9: marshal.v1.ListFleetResponse.agents:type_name -> marshal.v1.AgentState
	34, // 10: marshal.v1.AgentState.procs:type_name -> marshal.v1.ProcInfo
	6,  // 11: marshal.v1.AgentState.host:type_name -> marshal.v1.HostMetrics
	11, // 12: marshal.v1.MetricBatch.samples:type_name -> marshal.v1.MetricSample
	13, // 13: marshal.v1.LogBatch.lines:type_name -> marshal.v1.LogShipLine
	35, // 14: marshal.v1.FleetLogsHistoryRequest.stream:type_name -> marshal.v1.LogStream
	36, // 15: marshal.v1.FleetLogsHistoryResponse.lines:type_name -> marshal.v1.LogLine
	0,  // 16: marshal.v1.GitCredential.kind:type_name -> marshal.v1.CredentialKind
	21, // 17: marshal.v1.DirListing.entries:type_name -> marshal.v1.DirEntry
	37, // 18: marshal.v1.DeployRequest.app:type_name -> marshal.v1.AppSpec
	18, // 19: marshal.v1.DeployRequest.credential:type_name -> marshal.v1.GitCredential
	18, // 20: marshal.v1.RedeployRequest.credential:type_name -> marshal.v1.GitCredential
	1,  // 21: marshal.v1.CommitRequest.kind:type_name -> marshal.v1.CommitKind
	18, // 22: marshal.v1.CommitRequest.credential:type_name -> marshal.v1.GitCredential
	38, // 23: marshal.v1.ControlOp.stop:type_name -> marshal.v1.Selector
	38, // 24: marshal.v1.ControlOp.restart:type_name -> marshal.v1.Selector
	38, // 25: marshal.v1.ControlOp.delete:type_name -> marshal.v1.Selector
	39, // 26: marshal.v1.ControlOp.start:type_name -> marshal.v1.StartRequest
	24, // 27: marshal.v1.ControlOp.deploy:type_name -> marshal.v1.DeployRequest
	25, // 28: marshal.v1.ControlOp.redeploy:type_name -> marshal.v1.RedeployRequest
	19, // 29: marshal.v1.ControlOp.list_dir:type_name -> marshal.v1.ListDirRequest
	20, // 30: marshal.v1.ControlOp.read_file:type_name -> marshal.v1.ReadFileRequest
	26, // 31: marshal.v1.ControlOp.commit:type_name -> marshal.v1.CommitRequest
	38, // 32: marshal.v1.ControlOp.reload:type_name -> marshal.v1.Selector
	38, // 33: marshal.v1.ControlOp.reset:type_name -> marshal.v1.Selector
	38, // 34: marshal.v1.ControlOp.flush:type_name -> marshal.v1.Selector
	34, // 35: marshal.v1.ControlResult.procs:type_name -> marshal.v1.ProcInfo
	22, // 36: marshal.v1.ControlResult.dir:type_name -> marshal.v1.DirListing
	23, // 37: marshal.v1.ControlResult.file:type_name -> marshal.v1.FileContent
	27, // 38: marshal.v1.ControlResult.commit:type_name -> marshal.v1.CommitResult
	28, // 39: marshal.v1.Command.op:type_name -> marshal.v1.ControlOp
	29, // 40: marshal.v1.CommandResult.result:type_name -> marshal.v1.ControlResult
	28, // 41: marshal.v1.FleetControlRequest.op:type_name -> marshal.v1.ControlOp
	29, // 42: marshal.v1.FleetControlResponse.result:type_name -> marshal.v1.ControlResult
	2,  // 43: marshal.v1.Fleet.Connect:input_type -> marshal.v1.AgentMessage
	8,  // 44: marshal.v1.Fleet.ListFleet:input_type -> marshal.v1.ListFleetRequest
	17, // 45: marshal.v1.Fleet.FleetMetricsHistory:input_type -> marshal.v1.FleetMetricsHistoryRequest
	15, // 46: marshal.v1.Fleet.FleetLogsHistory:input_type -> marshal.v1.FleetLogsHistoryRequest
	32, // 47: marshal.v1.Fleet.FleetControl:input_type -> marshal.v1.FleetControlRequest
	3,  // 48: marshal.v1.Fleet.Connect:output_type -> marshal.v1.ServerMessage
	9,  // 49: marshal.v1.Fleet.ListFleet:output_type -> marshal.v1.ListFleetResponse
	40, // 50: marshal.v1.Fleet.FleetMetricsHistory:output_type -> marshal.v1.MetricsHistoryResponse
	16, // 51: marshal.v1.Fleet.FleetLogsHistory:output_type -> marshal.v1.FleetLogsHistoryResponse
	33, // 52: marshal.v1.Fleet.FleetControl:output_type -> marshal.v1.FleetControlResponse
	48, // [48:53] is the sub-list for method output_type
	43, // [43:48] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_marshal_v1_fleet_proto_init() }
func file_marshal_v1_fleet_proto_init() {
	if File_marshal_v1_fleet_proto != nil {
		return
	}
	file_marshal_v1_daemon_proto_init()
	file_marshal_v1_fleet_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Snapshot)(nil),
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_Logs)(nil),
		(*AgentMessage_Result)(nil),
	}
	file_marshal_v1_fleet_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_HelloAck)(nil),
		(*ServerMessage_Command)(nil),
	}
	file_marshal_v1_fleet_proto_msgTypes[26].OneofWrappers = []any{
		(*ControlOp_Stop)(nil),
		(*ControlOp_Restart)(nil),
		(*ControlOp_Delete)(nil),
		(*ControlOp_Start)(nil),
		(*ControlOp_Deploy)(nil),
		(*ControlOp_Redeploy)(nil),
		(*ControlOp_ListDir)(nil),
		(*ControlOp_ReadFile)(nil),
		(*ControlOp_Commit)(nil),
		(*ControlOp_Reload)(nil),
		(*ControlOp_Reset_)(nil),
		(*ControlOp_Flush)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marshal_v1_fleet_proto_rawDesc), len(file_marshal_v1_fleet_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marshal_v1_fleet_proto_goTypes,
		DependencyIndexes: file_marshal_v1_fleet_proto_depIdxs,
		EnumInfos:         file_marshal_v1_fleet_proto_enumTypes,
		MessageInfos:      file_marshal_v1_fleet_proto_msgTypes,
	}.Build()
	File_marshal_v1_fleet_proto = out.File
	file_marshal_v1_fleet_proto_goTypes = nil
	file_marshal_v1_fleet_proto_depIdxs = nil
}
