// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: marshal/v1/fleet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Snapshot
	//	*AgentMessage_Metrics
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetSnapshot() *StateSnapshot {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *MetricBatch {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // sent once on connect
}

type AgentMessage_Snapshot struct {
	Snapshot *StateSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"` // full process-state snapshot (periodic)
}

type AgentMessage_Metrics struct {
	Metrics *MetricBatch `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"` // raw CPU/mem samples (M8)
}

func (*AgentMessage_Hello) isAgentMessage_Msg() {}

func (*AgentMessage_Snapshot) isAgentMessage_Msg() {}

func (*AgentMessage_Metrics) isAgentMessage_Msg() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_HelloAck
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"` // reserved: command messages land here in M9
}

func (*ServerMessage_HelloAck) isServerMessage_Msg() {}

type Hello struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentName      string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	MarshalVersion string                 `protobuf:"bytes,2,opt,name=marshal_version,json=marshalVersion,proto3" json:"marshal_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *Hello) GetMarshalVersion() string {
	if x != nil {
		return x.MarshalVersion
	}
	return ""
}

type HelloAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LastMetricTsMs int64                  `protobuf:"varint,1,opt,name=last_metric_ts_ms,json=lastMetricTsMs,proto3" json:"last_metric_ts_ms,omitempty"` // server's stored high-water-mark for this agent (0 = none)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetLastMetricTsMs() int64 {
	if x != nil {
		return x.LastMetricTsMs
	}
	return 0
}

type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Procs         []*ProcInfo            `protobuf:"bytes,1,rep,name=procs,proto3" json:"procs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *StateSnapshot) GetProcs() []*ProcInfo {
	if x != nil {
		return x.Procs
	}
	return nil
}

type ListFleetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFleetRequest) Reset() {
	*x = ListFleetRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFleetRequest) ProtoMessage() {}

func (x *ListFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFleetRequest.ProtoReflect.Descriptor instead.
func (*ListFleetRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{5}
}

type ListFleetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentState          `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFleetResponse) Reset() {
	*x = ListFleetResponse{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFleetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFleetResponse) ProtoMessage() {}

func (x *ListFleetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFleetResponse.ProtoReflect.Descriptor instead.
func (*ListFleetResponse) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *ListFleetResponse) GetAgents() []*AgentState {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Connected     bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	LastSeenUnix  int64                  `protobuf:"varint,3,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	Procs         []*ProcInfo            `protobuf:"bytes,4,rep,name=procs,proto3" json:"procs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *AgentState) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentState) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *AgentState) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *AgentState) GetProcs() []*ProcInfo {
	if x != nil {
		return x.Procs
	}
	return nil
}

// One stored metric row, flattened to map 1:1 to a metricstore row.
type MetricSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // "app#instance"
	Cpu           float64                `protobuf:"fixed64,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem           int64                  `protobuf:"varint,4,opt,name=mem,proto3" json:"mem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *MetricSample) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *MetricSample) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MetricSample) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *MetricSample) GetMem() int64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*MetricSample        `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *MetricBatch) GetSamples() []*MetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type FleetMetricsHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"` // app name or "name#instance" label
	SinceMs       int64                  `protobuf:"varint,3,opt,name=since_ms,json=sinceMs,proto3" json:"since_ms,omitempty"`
	BucketMs      int64                  `protobuf:"varint,4,opt,name=bucket_ms,json=bucketMs,proto3" json:"bucket_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetMetricsHistoryRequest) Reset() {
	*x = FleetMetricsHistoryRequest{}
	mi := &file_marshal_v1_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMetricsHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMetricsHistoryRequest) ProtoMessage() {}

func (x *FleetMetricsHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_v1_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMetricsHistoryRequest.ProtoReflect.Descriptor instead.
func (*FleetMetricsHistoryRequest) Descriptor() ([]byte, []int) {
	return file_marshal_v1_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *FleetMetricsHistoryRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *FleetMetricsHistoryRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *FleetMetricsHistoryRequest) GetSinceMs() int64 {
	if x != nil {
		return x.SinceMs
	}
	return 0
}

func (x *FleetMetricsHistoryRequest) GetBucketMs() int64 {
	if x != nil {
		return x.BucketMs
	}
	return 0
}

var File_marshal_v1_fleet_proto protoreflect.FileDescriptor

const file_marshal_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"\x16marshal/v1/fleet.proto\x12\n" +
	"marshal.v1\x1a\x17marshal/v1/daemon.proto\"\xae\x01\n" +
	"\fAgentMessage\x12)\n" +
	"\x05hello\x18\x01 \x01(\v2\x11.marshal.v1.HelloH\x00R\x05hello\x127\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.marshal.v1.StateSnapshotH\x00R\bsnapshot\x123\n" +
	"\ametrics\x18\x03 \x01(\v2\x17.marshal.v1.MetricBatchH\x00R\ametricsB\x05\n" +
	"\x03msg\"K\n" +
	"\rServerMessage\x123\n" +
	"\thello_ack\x18\x01 \x01(\v2\x14.marshal.v1.HelloAckH\x00R\bhelloAckB\x05\n" +
	"\x03msg\"O\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12'\n" +
	"\x0fmarshal_version\x18\x02 \x01(\tR\x0emarshalVersion\"5\n" +
	"\bHelloAck\x12)\n" +
	"\x11last_metric_ts_ms\x18\x01 \x01(\x03R\x0elastMetricTsMs\";\n" +
	"\rStateSnapshot\x12*\n" +
	"\x05procs\x18\x01 \x03(\v2\x14.marshal.v1.ProcInfoR\x05procs\"\x12\n" +
	"\x10ListFleetRequest\"C\n" +
	"\x11ListFleetResponse\x12.\n" +
	"\x06agents\x18\x01 \x03(\v2\x16.marshal.v1.AgentStateR\x06agents\"\x9b\x01\n" +
	"\n" +
	"AgentState\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12$\n" +
	"\x0elast_seen_unix\x18\x03 \x01(\x03R\flastSeenUnix\x12*\n" +
	"\x05procs\x18\x04 \x03(\v2\x14.marshal.v1.ProcInfoR\x05procs\"]\n" +
	"\fMetricSample\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x04 \x01(\x03R\x03mem\"A\n" +
	"\vMetricBatch\x122\n" +
	"\asamples\x18\x01 \x03(\v2\x18.marshal.v1.MetricSampleR\asamples\"\x8f\x01\n" +
	"\x1aFleetMetricsHistoryRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x19\n" +
	"\bsince_ms\x18\x03 \x01(\x03R\asinceMs\x12\x1b\n" +
	"\tbucket_ms\x18\x04 \x01(\x03R\bbucketMs2\xf8\x01\n" +
	"\x05Fleet\x12B\n" +
	"\aConnect\x12\x18.marshal.v1.AgentMessage\x1a\x19.marshal.v1.ServerMessage(\x010\x01\x12H\n" +
	"\tListFleet\x12\x1c.marshal.v1.ListFleetRequest\x1a\x1d.marshal.v1.ListFleetResponse\x12a\n" +
	"\x13FleetMetricsHistory\x12&.marshal.v1.FleetMetricsHistoryRequest\x1a\".marshal.v1.MetricsHistoryResponseB\x18Z\x16marshal/internal/pb;pbb\x06proto3"

var (
	file_marshal_v1_fleet_proto_rawDescOnce sync.Once
	file_marshal_v1_fleet_proto_rawDescData []byte
)

func file_marshal_v1_fleet_proto_rawDescGZIP() []byte {
	file_marshal_v1_fleet_proto_rawDescOnce.Do(func() {
		file_marshal_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marshal_v1_fleet_proto_rawDesc), len(file_marshal_v1_fleet_proto_rawDesc)))
	})
	return file_marshal_v1_fleet_proto_rawDescData
}

var file_marshal_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_marshal_v1_fleet_proto_goTypes = []any{
	(*AgentMessage)(nil),               // 0: marshal.v1.AgentMessage
	(*ServerMessage)(nil),              // 1: marshal.v1.ServerMessage
	(*Hello)(nil),                      // 2: marshal.v1.Hello
	(*HelloAck)(nil),                   // 3: marshal.v1.HelloAck
	(*StateSnapshot)(nil),              // 4: marshal.v1.StateSnapshot
	(*ListFleetRequest)(nil),           // 5: marshal.v1.ListFleetRequest
	(*ListFleetResponse)(nil),          // 6: marshal.v1.ListFleetResponse
	(*AgentState)(nil),                 // 7: marshal.v1.AgentState
	(*MetricSample)(nil),               // 8: marshal.v1.MetricSample
	(*MetricBatch)(nil),                // 9: marshal.v1.MetricBatch
	(*FleetMetricsHistoryRequest)(nil), // 10: marshal.v1.FleetMetricsHistoryRequest
	(*ProcInfo)(nil),                   // 11: marshal.v1.ProcInfo
	(*MetricsHistoryResponse)(nil),     // 12: marshal.v1.MetricsHistoryResponse
}
var file_marshal_v1_fleet_proto_depIdxs = []int32{
	2,  // 0: marshal.v1.AgentMessage.hello:type_name -> marshal.v1.Hello
	4,  // 1: marshal.v1.AgentMessage.snapshot:type_name -> marshal.v1.StateSnapshot
	9,  // 2: marshal.v1.AgentMessage.metrics:type_name -> marshal.v1.MetricBatch
	3,  // 3: marshal.v1.ServerMessage.hello_ack:type_name -> marshal.v1.HelloAck
	11, // 4: marshal.v1.StateSnapshot.procs:type_name -> marshal.v1.ProcInfo
	7,  // 5: marshal.v1.ListFleetResponse.agents:type_name -> marshal.v1.AgentState
	11, // 6: marshal.v1.AgentState.procs:type_name -> marshal.v1.ProcInfo
	8,  // 7: marshal.v1.MetricBatch.samples:type_name -> marshal.v1.MetricSample
	0,  // 8: marshal.v1.Fleet.Connect:input_type -> marshal.v1.AgentMessage
	5,  // 9: marshal.v1.Fleet.ListFleet:input_type -> marshal.v1.ListFleetRequest
	10, // 10: marshal.v1.Fleet.FleetMetricsHistory:input_type -> marshal.v1.FleetMetricsHistoryRequest
	1,  // 11: marshal.v1.Fleet.Connect:output_type -> marshal.v1.ServerMessage
	6,  // 12: marshal.v1.Fleet.ListFleet:output_type -> marshal.v1.ListFleetResponse
	12, // 13: marshal.v1.Fleet.FleetMetricsHistory:output_type -> marshal.v1.MetricsHistoryResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_marshal_v1_fleet_proto_init() }
func file_marshal_v1_fleet_proto_init() {
	if File_marshal_v1_fleet_proto != nil {
		return
	}
	file_marshal_v1_daemon_proto_init()
	file_marshal_v1_fleet_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Snapshot)(nil),
		(*AgentMessage_Metrics)(nil),
	}
	file_marshal_v1_fleet_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_HelloAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marshal_v1_fleet_proto_rawDesc), len(file_marshal_v1_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marshal_v1_fleet_proto_goTypes,
		DependencyIndexes: file_marshal_v1_fleet_proto_depIdxs,
		MessageInfos:      file_marshal_v1_fleet_proto_msgTypes,
	}.Build()
	File_marshal_v1_fleet_proto = out.File
	file_marshal_v1_fleet_proto_goTypes = nil
	file_marshal_v1_fleet_proto_depIdxs = nil
}
